name: flutter_avif
description: Avif support for Flutter.
version: 0.0.1
repository: https://github.com/yekeskin/flutter_avif

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.38.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  plugin:
    platforms:
      android:
        package: com.teknorota.flutter_avif
        pluginClass: FlutterAvifPlugin
      ios:
        pluginClass: FlutterAvifPlugin
      macos:
        pluginClass: FlutterAvifPlugin
