name: flutter_avif_platform_interface
description: Common platform interface for the flutter_avif plugin.
version: 1.0.0
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_platform_interface

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.38.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
