name: flutter_avif_platform_interface
description: Common platform interface for the flutter_avif plugin.
version: 1.4.0
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_platform_interface

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^1.2.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: "1.27.0"
  meta: 1.7.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: 4.1.3